title: Meow Runner
description: Meow runner is a remake of the classic Chrome offline dinosaur game, redesigned using cat theme. 
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
    values:
      layout: default
